### ISSUE TITLE
Build: package requirements

### ISSUE THREAD

**Issue by branrickman** [branrickman/readthedocs-tutorial#1]
I'm not sure where to find the package requirements to build the docs. There is an 'environment' listed in the repo, but it's pickled.

**Comment by branrickman** [comment]
in particular, running into issues with 'automodule'

```
Error

Command /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/envs/latest/bin/python -m sphinx -T -E -W --keep-going -b html -d _build/doctrees -D language=en . _build/html failed: Running Sphinx v4.4.0 loading translations [en]... done making output directory... done building [mo]: targets for 0 po files that are out of date building [html]: targets for 13 source files that are out of date updating environment: [new config] 13 added, 0 changed, 0 removed reading sources... [ 7%] sphinx/source/index reading sources... [ 15%] sphinx/source/medicaid_utils reading sources... [ 23%] sphinx/source/medicaid_utils.adapted_algorithms reading sources... [ 30%] sphinx/source/medicaid_utils.adapted_algorithms.py_betos reading sources... [ 38%] sphinx/source/medicaid_utils.adapted_algorithms.py_cdpsmrx reading sources... [ 46%] sphinx/source/medicaid_utils.adapted_algorithms.py_ed_pqi reading sources... [ 53%] sphinx/source/medicaid_utils.adapted_algorithms.py_elixhauser reading sources... [ 61%] sphinx/source/medicaid_utils.adapted_algorithms.py_ip_pqi reading sources... [ 69%] sphinx/source/medicaid_utils.adapted_algorithms.py_low_value_care reading sources... [ 76%] sphinx/source/medicaid_utils.adapted_algorithms.py_nyu_billings reading sources... [ 84%] sphinx/source/medicaid_utils.adapted_algorithms.py_pmca reading sources... [ 92%] sphinx/source/modules reading sources... [100%] sphinx/source/overview /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_betos.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_betos.betos_proc_codes :members: assign_betos_cat :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_cdpsmrx.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_cdpsmrx.cdps_rx_risk_adjustment :members: cdps_rx_risk_adjust :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_ed_pqi.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_ed_pqi.ed_pqi :members: get_ed_pqis :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_elixhauser.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_elixhauser.elixhauser_comorbidity :members: score :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_ip_pqi.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_ip_pqi.prevention_quality_indicators :members: pqirecode :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_low_value_care.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_low_value_care.low_value_care :members: :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_nyu_billings.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_nyu_billings.billings_ed :members: get_nyu_ed_proba :undoc-members: :show-inheritance: /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/sphinx/source/medicaid_utils.adapted_algorithms.py_pmca.rst:10: ERROR: Unknown directive type "automodule". .. automodule:: medicaid_utils.adapted_algorithms.py_pmca.pmca :members: pmca_chronic_conditions :undoc-members: :show-inheritance: Traceback (most recent call last): File "/home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 284, in build_main app.build(args.force_all, filenames) File "/home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 337, in build self.builder.build_update() File "/home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 294, in build_update self.build(to_build, File "/home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 308, in build updated_docnames = set(self.read()) File "/home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/envs/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 418, in read raise SphinxError('root file %s not found' % sphinx.errors.SphinxError: root file /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/index.rst not found Sphinx error: root file /home/docs/checkouts/readthedocs.org/user_builds/medicaid-utils/checkouts/latest/docs/index.rst not found
```
